class Patient {
  final int id;
  final String name;
  final String dob;
  final String gender;
  final String contact;
  final String folderNumber; // Generated by receptionist

  Patient({
    required this.id,
    required this.name,
    required this.dob,
    required this.gender,
    required this.contact,
    required this.folderNumber,
  });

  factory Patient.fromJson(Map<String, dynamic> json) {
    return Patient(
      id: json['id'],
      name: json['name'],
      dob: json['dob'],
      gender: json['gender'],
      contact: json['contact'],
      folderNumber: json['folder_number'],
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'dob': dob,
    'gender': gender,
    'contact': contact,
    'folder_number': folderNumber,
  };
}